name: INE
channels:
    - conda-forge
dependencies:
    - python=3.8
    - pandas=1
    - pip
    - numpy
    - jupyter
    - jupyterlab
    - rise
    - matplotlib
    - xlrd
    - requests
    - sqlalchemy
    - h5py
    - psycopg2
    - pytables
    - lxml
    - jsonpickle
    - flask
    - pytest
    - pytest-xdist
    - bs4
    - scrapy
    - selenium
    - tabulate
    - mysql-connector-python
    - more-itertools
    - scikit-learn
    - pip:
        - csvkit
        - html5lib
        - asyncpg
        - pg8000
        - aiopg
        - nest_asyncio
        - bash_kernel
        - PyMySQL[rsa]
        - striprtf
